use std::collections::HashMap;
use std::sync::Arc;

use crate::consensus_support::{LengthSummary, PanelProvenanceCounts};
use crate::plugins::PluginDefinition;
use crate::rnaseq::RnaseqMetrics;
use crate::scoring_support::ComponentScores;
use crate::taxonomy::TaxonomyEvidence;
use crate::*;

#[derive(Clone)]
pub(crate) struct RenderContext {
    pub(crate) stats: Arc<HashMap<String, diamond::DiamondHitStats>>,
    pub(crate) intrinsic_map: Arc<HashMap<String, (metrics::IntrinsicMetrics, Vec<u8>)>>,
    pub(crate) alignment_map: Arc<HashMap<String, mafft::AlignmentMetrics>>,
    pub(crate) hmmsum_map: Arc<HashMap<String, hmmer::HmmscanSummary>>,
    pub(crate) taxsum_map: Arc<HashMap<String, Option<TaxonomyEvidence>>>,
    pub(crate) taxonomy_resolver: Option<Arc<taxonomy::TaxonomyResolver>>,
    pub(crate) genomic_map: Option<Arc<HashMap<String, genomic::GenomicMetrics>>>,
    pub(crate) scores_map: Arc<HashMap<String, (f64, String)>>,
    pub(crate) raw_scores_map: Arc<HashMap<String, f64>>,
    pub(crate) comp_map: Arc<HashMap<String, ComponentScores>>,
    pub(crate) arch_map: Arc<HashMap<String, f64>>,
    pub(crate) len_map: Arc<HashMap<String, LengthSummary>>,
    pub(crate) orphan_map: Arc<HashMap<String, hmmer::OrphanAnalysis>>,
    pub(crate) structvar_map: Arc<HashMap<String, structvar::StructVar>>,
    pub(crate) panel_prov_map: Arc<HashMap<String, PanelProvenanceCounts>>,
    pub(crate) cov_delta_thresh: f64,
    pub(crate) taxonomy_enabled: bool,
    pub(crate) taxonomy_expected_domain: Option<String>,
    pub(crate) taxonomy_warn_non_target_min_frac: f64,
    pub(crate) taxonomy_warn_non_target_min_hits: usize,
    pub(crate) taxonomy_warn_non_target_strong_frac: f64,
    pub(crate) taxonomy_warn_non_target_strong_hits: usize,
    pub(crate) taxonomy_warn_genus_min_frac: f64,
    pub(crate) taxonomy_warn_genus_min_hits: usize,
    pub(crate) taxonomy_low_coverage_frac: f64,
    pub(crate) orphan_analysis_enabled: bool,
    pub(crate) csv_verbose: bool,
    pub(crate) mafft_missing_exon_thresh: usize,
    pub(crate) mafft_retained_intron_thresh: usize,
    pub(crate) features_string: String,
    pub(crate) plugins: Vec<PluginDefinition>,
    pub(crate) rhai_runtime: Option<rhai_rules::RhaiRuntime>,
    pub(crate) rnaseq_map: Arc<HashMap<String, RnaseqMetrics>>,
    pub(crate) rnaseq_enabled: bool,
    pub(crate) th_high: f64,
    pub(crate) th_med: f64,
}

#[allow(dead_code)]
#[derive(Clone, Debug, Default)]
pub struct ScoreCard {
    pub gene_id: String,
    pub hits_count: usize,
    pub panel_swissprot: usize,
    pub panel_refprot: usize,
    pub panel_cluster: usize,
    pub top_hit: String,
    pub top_bitscore: f64,
    pub top_evalue: f64,
    pub top_qcov: f64,
    pub top_scov: f64,
    pub bitscore_density: f64,
    pub coverage_delta: f64,
    pub coverage_ratio: f64,
    pub subject_cov_score: f64,
    pub subject_cov_penalty: f64,
    pub fusion_split: bool,
    pub structvar_multiplier: f64,
    pub final_score: f64,
    pub homology_score: f64,
    pub intrinsic_score: f64,
    pub taxonomy_score: Option<f64>,
    pub domains_score: Option<f64>,
    pub domains_arch_score: f64,
    pub orphan_domain_score: f64,
    pub length_score: f64,
    pub length_ratio: f64,
    pub length_class: String,
    pub expected_len_min: Option<f64>,
    pub expected_len_max: Option<f64>,
    pub length_in_expected_range: Option<bool>,
    pub length_panel_n: Option<usize>,
    pub conserved_regions_score: f64,
    pub termini_score: f64,
    pub divergence_score: f64,
    pub mafft_enabled: bool,
    pub conserved_fraction: f64,
    pub pairwise_identity: f64,
    pub panel_pairwise_identity: f64,
    pub divergence_ratio: f64,
    pub sequences_aligned: usize,
    pub query_gap_fraction: f64,
    pub gap_run_count: usize,
    pub max_gap_run: usize,
    pub missing_exon_run: usize,
    pub retained_intron_run: usize,
    pub start_concordance: f64,
    pub start_class: String,
    pub end_concordance: f64,
    pub end_class: String,
    pub structvar_class: String,
    pub structvar_gap: Option<usize>,
    pub orphan_status: String,
    pub taxonomy_contamination: Option<f64>,
    pub taxonomy_support: usize,
    pub taxonomy_considered: usize,
    pub taxonomy_support_frac: f64,
    pub consensus_taxon: String,
    pub taxonomy_rank: String,
    pub taxonomy_status: String,
    pub taxonomy_domain: String,
    pub taxonomy_genus: String,
    pub genomic_introns: Option<usize>,
    pub genomic_splice_canonical: Option<usize>,
    pub genomic_splice_noncanonical: Option<usize>,
    pub genomic_splice_weird: Option<usize>,
    pub genomic_score: f64,
    pub rnaseq_score: f64,
    pub rnaseq_tpm: String,
    pub rnaseq_num_reads: String,
    pub classification_base: String,
    pub classification_final: String,
    pub plugin_penalty: f64,
    pub plugin_count: usize,
    pub plugin_names: String,
    pub plugin_scores: String,
    pub plugin_penalties: String,
    pub plugin_metadata: String,
    pub warnings: String,
}

pub(crate) struct RenderedRecord {
    pub(crate) index: usize,
    pub(crate) json_line: String,
    pub(crate) csv_line: String,
    pub(crate) card: Option<ScoreCard>,
}
